### ISSUE TITLE
sbt-git seems abandoned

### ISSUE THREAD

**Issue by jason-yeo-paidy** [sbt/sbt-git#182]
Is this plugin still being maintained? The last release was in 2018. If the maintainers need help, I'm happy to help maintain it. 😄

**Comment by SethTisue** [comment]
@jason-yeo-paidy I now have merge rights in this repo. And yes, we would love to have help here. If you send PRs, I can merge them. You can also comment on existing PRs and suggest they be merged.

Note that because of the Bintray shutdown, we cannot currently publish this plugin. So the most immediate need here is a pull request that replaces sbt-bintray with sbt-ci-release. (You might see what happens at https://github.com/sbt/sbt-projectmatrix/issues/47 and copy it.)

Once you or another volunteer fixes the publishing, I can make sure the config gets the needed publishing secrets.

About CI, currently we are on Travis-CI. We could continue using that, or move to GitHub Actions, either way is fine.

**Comment by SethTisue** [comment]
see also #183

**Comment by eed3si9n** [comment]
You can check out https://github.com/sbt/sbt-pgp/tree/develop/.github/workflows for the reference implementation of how to hook up GitHub Actions.

I think sbt-git has been abandoned because it's no longer in fashion to use it among the core developers in sbt or sbt plugin community. sbt modules use https://github.com/dwijnand/sbt-dynver.

**Comment by SethTisue** [comment]
re: GitHub Actions, I've opened a separate help-wanted ticket at #184

**Comment by SethTisue** [comment]
@raboof's efforts to publish, at https://github.com/sbt/sbt-git/pull/188, seem to have stalled

**Comment by raboof** [comment]
> @raboof's efforts to publish, at #188, seem to have stalled

Actually 1.0.1 was released from CI :)

**Comment by SethTisue** [comment]
I'm going to close this, since we have a recent release.

See also my recent remarks on #168.

Help with reviewing PRs, triaging issues, and such, remains welcome from anyone who cares to participate.
