### ISSUE TITLE
Drop sbt 0.13 from the crossbuild

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt-git#187]
New versions of the plugin should be published for sbt 1.x only; there's isn't any point in paying the cost of cross building anymore.

**Comment by aadrian** [comment]
@SethTisue many PlayFramework based based projects still require SBT 0.13.x  since they can't easily just upgrade.

*(Unfortunately newer PlayFrameworks versions and plug-ins are not very backwards compatible, so many projects depending on them can't simply just use the latest versions that would work with SBT 1.x)*

**Comment by SethTisue** [comment]
Dropping sbt 0.13 from the crossbuild won't make anyone's existing projects stop working. If you're using sbt 0.13 and sbt-git together and they're working for you, then great! Stick with the versions you have. If you don't need to upgrade Play and sbt, why would you need to upgrade sbt-git?

**Comment by SethTisue** [comment]
And if for some reason you _do_ truly need some change in a newer sbt-git, you're free to fork the repo and build an sbt 0.13 version yourself. It's open source.

**Comment by limansky** [comment]
@SethTisue I've found that sbt-git is not published for sbt 0.13.x, however `crossSbtVersions` still contains 0.13.17. Is sbt 0.13.x support dropped already? If not, could you please publish the artifacts?

**Comment by raboof** [comment]
> @SethTisue I've found that sbt-git is not published for sbt 0.13.x, however `crossSbtVersions` still contains 0.13.17. Is sbt 0.13.x support dropped already? If not, could you please publish the artifacts?

I see the github publishing workflow we added indeed does `+publishSigned`, not `^publishSigned`, so indeed that'd only publish for sbt 1.x.

I guess you're asking in the context of https://github.com/limansky/sbt-git-flow-version ? Do you have a particular use case for not dropping sbt 0.13.x support there yet?

**Comment by limansky** [comment]
Hi @raboof. Yep, I'd like to upgrade dependencies in `sbt-git-flow-version`. I don't know how many users it has, and which sbt versions they use. But since I got both sbt versions support for free (no separate code required, no need to use specific API, etc), I don't see any reasons to not support 0.13.x in my case.

**Comment by SethTisue** [comment]
> Yep, I'd like to upgrade dependencies in sbt-git-flow-version. I don't know how many users it has, and which sbt versions they use

sbt 0.13 is highly antiquated at this point and I strongly recommend that _all_ sbt plugins stop supporting it unless there are _specific, pressing_ reasons to continue

**Comment by SethTisue** [comment]
PR: #191
