### ISSUE TITLE
Plan next release

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt-git#215]
What should the version number be? 1.0.3? 1.1.0?

**Comment by armanbilge** [comment]
I understand the publishing org changed in https://github.com/sbt/sbt-git/pull/205?

To me it seems like that will require a package name change and a breaking version bump to 2.0.0 to avoid classpath problems.

**Comment by SethTisue** [comment]
@eed3si9n have other sbt plugins that have changed publishing orgs also changed package names...?

**Comment by armanbilge** [comment]
sbt-pgp didn't: https://github.com/sbt/sbt-pgp/releases/tag/v2.1.2

IDK. sbt-git seems like a foundational plugin that might power versioning plugins, gh-pages publishing plugins, what have you. Seems ripe for triangle dependencies.

**Comment by eed3si9n** [comment]
It's a mix. I imagine that some projects are more comfortable using original authors domain as package names because we know them personally while others might opt for more neutral package name for consistency etc? Here are non-exhaustive list:

- sbt-pgp. **unchanged** `com.jsuereth.sbtpgp` - https://github.com/sbt/sbt-pgp/blob/develop/sbt-pgp/src/main/scala/com/jsuereth/sbtpgp/SbtPgp.scala
- junit-interface. **unchanged** `com.novocode.junit` - https://github.com/sbt/junit-interface/blob/develop/src/main/java/com/novocode/junit/JUnitFramework.java
- sbt-avro. **changed** `com.github.sbt.avro` - https://github.com/sbt/sbt-avro/blob/master/src/main/scala/com/github/sbt/avro/SbtAvro.scala
- sbt-ci-release. **unchanged** `com.geirsson` - https://github.com/sbt/sbt-ci-release/blob/main/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala
- sbt-jacoco. **changed** `com.github.sbt.jacoco` - https://github.com/sbt/sbt-jacoco/blob/main/src/main/scala/com/github/sbt/jacoco/JacocoPlugin.scala
- sbt-jni. **changed** `com.github.sbt.jni` - https://github.com/sbt/sbt-jni/blob/main/plugin/src/main/scala/com/github/sbt/jni/plugins/JniNative.scala

**Comment by raboof** [comment]
> I understand the publishing org changed in #205?
> 
> To me it seems like that will require a package name change (...) to avoid classpath problems.

That's a great point, let's discuss that separately in #216

> and a breaking version bump to 2.0.0

Since the groupId changed I don't think we strictly need to, but I agree it might be nice.

**Comment by armanbilge** [comment]
Re the version bump: since Scala Steward knows about the group id change, downstreams will receive PRs updating them per usual. So a version bump is important to communicate to this breaking change IMO.

**Comment by armanbilge** [comment]
Sorry to be annoying, but any ideas how we can get unblocked? https://github.com/sbt/sbt-git/pull/218 is one way forward. Another way forward is to not care about eviction problems and plunge ahead of course :) all other ideas proposed so far require reviving the old group id and publication credentials.

**Comment by raboof** [comment]
Okay, so our options are:
* merge #218 and release 2.0.0, with the consequence that you cannot have 1.x and 2.x versions of sbt-git on the plugin classpath side-by-side
* merge #218, revert #205 and release 2.0.0, with the downside that we'd still want #205 in the future
* do not merge #218, introduce a ['transitional' 1.x](https://github.com/sbt/sbt-git/issues/216#issuecomment-1069075478), release 2.0.0, supporting both 1.x and 2.x side-by-side

I'm also OK with the first option (and its consequence). If no-one objects let's go for that.

**Comment by armanbilge** [comment]
Cool, seems the way forward is https://github.com/sbt/sbt-git/pull/218 and release 2.0.0. Thanks all!

**Comment by SethTisue** [comment]
tagged https://github.com/sbt/sbt-git/releases/tag/v2.0.0

publish job https://github.com/sbt/sbt-git/actions/runs/2059270141

artifacts are on their way to Maven Central

**Comment by armanbilge** [comment]
Thank you!!!

**Comment by SethTisue** [comment]
Thank you Eugene, Arnout, Arman
